spring:
  application:
    name: api-restful-backend
  datasource:
    url: jdbc:postgresql://bzcq6as90etbzc7rniia-postgresql.services.clever-cloud.com:50013/bzcq6as90etbzc7rniia
    username: ucjabh8f6f25n3vvii05
    password: mmEuTTuKPF7uaeFBdAtjHok8zcLNLd
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
