-.spring:
  application:
    name: api-restful-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/mycorhuila
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true
server:
  port: 8080
